# curl --location --request GET 'http://localhost:8080/redis/test'
GET http://localhost:8080/redis/test

### login 서버 에러나네.. 한번 한거라 그런가? -> 그건 또 아닌듯..
# curl --location --request GET 'localhost:8080/login/oauth2/code/kakao?code=hyxF4F7aHGmVIHBmzDw2429g5YPL7rfsZD2s2NcEepueC0x6KaMlwVLCBSuJCvfauLVqhworDR4AAAGGu5Jpsw'
GET localhost:8080/login/oauth2/code/kakao?code=Dru4jp-SOAfn3V_Y6rK5X8BrO7AKowE15MxnZEfNqnEEn_sC8DHyazUtTqKzp3t4mJx7Ogo9c5sAAAGG73AKvg

### accessToken 재발급
GET localhost:8080/login/reissueToken
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY3ODMxNjA1Mn0.QjIpLGSQVEB2eW6wdC34q4JojS0YUDd1q6W-86O4YNvxh4jRv4GBUlm81lX7WJZKRuMv3aDnH3Gd2MlUZmu3zQ
Content-Type: application/json

### 회원 조회
GET localhost:8080/api/user/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY3OTM5ODQ5N30.qW9JEam5JpkA6hTFhUyIi-FRZaLCPu648KTUbBjr-nSj2vFXDXIZK6BPbEIXTp_S16Z9cj72RCrJVBq0qWz91Q
Accept: application/json

### 회원 탈퇴
PUT localhost:8080/api/user
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY3OTM5ODQ5N30.qW9JEam5JpkA6hTFhUyIi-FRZaLCPu648KTUbBjr-nSj2vFXDXIZK6BPbEIXTp_S16Z9cj72RCrJVBq0qWz91Q
Content-Type: application/json

{
  "userId": 1,
  "withdrawalGroundsType": "errors"
}

### 모임 생성
POST http://localhost:8080/api/group
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY4MDg3ODk1OX0.8io_gEQo4jmn_ieW6doq2GGFcm9jqxyUx2q6aMQTPWD_uf-bWNKdiAKuuhNfvGVzZzeMDIIhFNh3V59u2dlk1g
Content-Type: application/json

{
  "title": "kkk의 스터디",
  "nickname": "aaa",
  "type": "스터디",
  "coverColor": "#f86565"
}

### 모임 내 본인 닉네임 조회
GET localhost:8080/api/group/2/participant
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMiIsImV4cCI6MTY3OTc1MjMzOX0.r06_nlkfsr5gO4CFt5zhvR4s01L44V8d3tW9j0cxwrvDlhYm6Nq_k8GYhv9MG3zoEgaPI8mrXYpTDHj-gN_LmA

### 이벤트 생성
POST localhost:8080/api/event/penalty
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY3OTc4MDE0OH0.WxnDUIEQzsTx7Hc19BN-zArh8RlBTgoXZO1qtGVgONo1y_wPTnjAMaeZmp3xuTJN1acCs0CPA3sNe9zZT4lmBg
Content-Type: application/json

{
  "groupId": 2,
  "userName": "kkk",
  "groundsDate": "2023.03.17",
  "payment": 170000,
  "grounds": "되라",
  "paymentType": "non"
}

### 이벤트 조회
GET http://localhost:8080/api/event/penalty/5
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY4MDUwODM1OX0.rmnvl0aZ9PHpnY_nJ3-GZHi6OV8aKG2O_NemnMHmJShsgx6QAVAotkkVCLtsn7ep_dAS6kMeLR-QR1g7UqZ_PA

### 이벤트 수정
POST http://localhost:8080/api/event/penalty/33
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY3OTc4MDE0OH0.WxnDUIEQzsTx7Hc19BN-zArh8RlBTgoXZO1qtGVgONo1y_wPTnjAMaeZmp3xuTJN1acCs0CPA3sNe9zZT4lmBg
Content-Type: application/json

{
  "groundsDate": "2023.03.26"
}

### 납부여부 변경
PATCH http://localhost:8080/api/event/penalty/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY3OTM5MTIwOH0.CyMPcZAijLmN1h0y62dsfEQXzIOCR5icvJSaLafgCtfb0skY_HtzUvLtzVAeUnIwOnWBl1P6oV-P2DAXDSQbeQ
Content-Type: application/json

{
  "paymentType": "con"
}

### 이벤트 삭제
PUT http://localhost:8080/api/event/penalty/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY3OTM5MTIwOH0.CyMPcZAijLmN1h0y62dsfEQXzIOCR5icvJSaLafgCtfb0skY_HtzUvLtzVAeUnIwOnWBl1P6oV-P2DAXDSQbeQ

### 이벤트 리스트
#GET http://localhost:8080/api/event/penalty/list/1?paymentType=full&page=0
GET http://localhost:8080/api/event/penalty/list/1?year=2023&month=3&day=26&page=0
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY3OTg3NzIwM30.jXd420EDaPK_bq3ysqPf34GWg1w7V5h49qzFDm4rM1goo7PcB9PzXlXjD5VFz5Tkl-sy7fgPEZMCHzgJlCIJOQ

### 달별 납부여부 조회
GET http://localhost:8080/api/event/penalty/mstatus/1?year=2023&month=3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY3OTc5MjQ4OX0.32IQsPqbIwXaR9FRx_-1tWT3M-vuTRR7jPDGsTfz-Kjp_wnSJIsVmH4Co55muH6XLXd39a8fnGtgSc4CZ8poIQ


