# curl --location --request GET 'http://localhost:8080/redis/test'
GET http://localhost:8080/redis/test

### login 서버 에러나네.. 한번 한거라 그런가?
# curl --location --request GET 'localhost:8080/login/oauth2/code/kakao?code=hyxF4F7aHGmVIHBmzDw2429g5YPL7rfsZD2s2NcEepueC0x6KaMlwVLCBSuJCvfauLVqhworDR4AAAGGu5Jpsw'
GET localhost:8080/login/oauth2/code/kakao?code=Dru4jp-SOAfn3V_Y6rK5X8BrO7AKowE15MxnZEfNqnEEn_sC8DHyazUtTqKzp3t4mJx7Ogo9c5sAAAGG73AKvg

### accessToken 재발급
GET localhost:8080/login/reissueToken
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY3ODMxNjA1Mn0.QjIpLGSQVEB2eW6wdC34q4JojS0YUDd1q6W-86O4YNvxh4jRv4GBUlm81lX7WJZKRuMv3aDnH3Gd2MlUZmu3zQ
Content-Type: application/json

###



### 회원 조회
# curl --location --request GET 'localhost:8080/api/user/1'
#--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY3ODE5MzA5M30.FYSDZuTm0AceNYbzlC_8K25v-29P2umQA3-YQ9PI7rbHXWz3thjL5F50XOnkMN_TW4wO2_imS_fqe7Kldf_WNg'
GET localhost:8080/api/user/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY3ODMxODA4Nn0.LagjWrMyV9fGn17E-vjmL7NoCPbXkfGWvuTozROYtnYMXva__onsCgfMz3D1iZtYlOd5sIHB79Bt8fp1DKuOVQ
Accept: application/json

### 회원 탈퇴
PUT localhost:8080/api/user
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY3ODMxODA4Nn0.LagjWrMyV9fGn17E-vjmL7NoCPbXkfGWvuTozROYtnYMXva__onsCgfMz3D1iZtYlOd5sIHB79Bt8fp1DKuOVQ
Content-Type: application/json

{
  "userId": 1,
  "withdrawalGroundsType": 3
}

### 모임 생성
POST http://localhost:8080/api/group
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY3OTI5OTQyMn0.J_Zl3NeznzOEt8HI50oXu7OYlW1yB8jkeJchzRYgLolfWDShw5heMVAqs8UaAHmUd_AVlqnsfnYfgW6nyZmQfQ
Content-Type: application/json

{
  "groupName": "test",
  "myName": "kkk",
  "type": "스터디",
  "coverColor": "#f86565"
}

### 이벤트 생성
POST createEvent
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY3OTMxNTg0MX0.sRcBft7YprBtun5e7JJF-fg6C1K5bdlef_cTnNLYRZZfFj-GWAYMH--sy_mtLJp9tCc8nu9zUjfmb6pA65-VEg
Content-Type: application/json

{
  "userName": "kkk",
  "groundsDate": "2023-03-18 23:42:43",
  "payment": 1000,
  "grounds": "지각",
  "paymentType": "non"
}

### 이벤트 조회
GET http://localhost:8080/api/event/penalty/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImlkIjoiMSIsImV4cCI6MTY3OTMzNTEyN30.fpL_e4zGGQAuJRum5HVr3knS9PIkTjqxqLJVB0AbM8Ovp0DpaPdbA_ediTZnSnuBrsRgVgnYUImq5aO6GC7uAA

###



