# ci

on:
push: 
  branches:
    - 'main'
    - 'develop'
    - 'feature/*'
pull_request:
  branches:
    - 'main'
    - 'develop'
    - 'feature/*'

jobs:
  build: 
    runs-on: ubuntu-latest # 실행 환경 지정

    steps:
      - uses: actions/checkout@v2 # github action 버전 지정(major version)

      - name: Set up JDK 11 # JAVA 버전 지정
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database: 'sosim_db'
          mysql user: 'root'
          mysql password: '1234'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
       ## create application-database.yaml
      - name: make application-database.yaml
        run: |
          # create application-database.yaml
           cd ./src/main/resources
          # application-database.yaml 파일 생성
           touch ./application-database.yaml
          # GitHub-Actions 에서 설정한 값을 application-database.yaml 파일에 쓰기
          echo "${{ secrets.DATABASE }}" >> ./application-database.yaml
        shell: bash
      
      
      - name: Build with Gradle # 실제 application build(-x 옵션을 통해 test는 제외)
        run: ./gradlew build -x test

      - name: Test with Gradle # test application build
        run: ./gradlew test

      - name: Publish Unit Test Results # test 후 result를 보기 위해 추가
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }} # test가 실패해도 report를 남기기 위해 설정
        with:
          files: build/test-results/**/*.xml